#!/bin/sh

#
# WORKSPACE 1 - BROWSER
#
# i3-msg 'workspace "1"; append_layout ~/.config/i3/workspaces/1.json' &
# google-chrome-stable &
# firefox &

#
# WORKSPACE 3 - MEDIA
#
# i3-msg 'workspace \"3\"; append_layout ~/.config/i3/workspaces/3.json' &
# xfce4-terminal --hide-menubar --role="media-file-manager" -e ranger &
# deluge-gtk &
# Shinjiru &

#
# WORKSPACE 4 - SONGS
#
# i3-msg 'workspace "4"; append_layout ~/.config/i3/workspaces/4.json' &
# xfce4-terminal --hide-menubar --role="songs-player" -e cmus &
# xfce4-terminal --hide-menubar --role="songs-file-manager" -e ranger &
# xfce4-terminal --hide-menubar --role="songs-spectrum" -e cava &
# xfce4-terminal --hide-menubar --role="songs-spotify" &

#
# WORKSPACE 8 - SOCIAL
#
# i3-msg 'workspace "8"; append_layout ~/.config/i3/workspaces/8.json' &
# slack &
# discord &
# thunderbird &

#
# WORSPACE 9 - CIRNO
#
# i3-msg 'workspace "9"; append_layout ~/.config/i3/workspaces/9.json' &
# xfce4-terminal --hide-menubar --role="cirno-1" --default-working-directory="/home/seiji/.config" &
# xfce4-terminal --hide-menubar --role="cirno-2" --default-working-directory="/home/seiji/.config" &
# xfce4-terminal --hide-menubar --role="cirno-3" --default-working-directory="/home/seiji/.config" &
# xfce4-terminal --hide-menubar --role="cirno-4" --default-working-directory="/home/seiji/.config" &
# xfce4-terminal --hide-menubar --role="cirno-6" --default-working-directory="/home/seiji/.config" &
# xfce4-terminal --hide-menubar --role="cirno-7" --default-working-directory="/home/seiji/.config" &
# xfce4-terminal --hide-menubar --role="cirno-8" --default-working-directory="/home/seiji/.config" &
# xfce4-terminal --hide-menubar --role="cirno-9" --default-working-directory="/home/seiji/.config" &

#
# WORKSPACE 10 - TERMINALS
#
# i3-msg 'workspace "10"; append_layout ~/.config/i3/workspaces/10.json' &
# xfce4-terminal --hide-menubar --role="terminal-1" -e ranger &
# xfce4-terminal --hide-menubar --role="terminal-2" -e ranger &
# xfce4-terminal --hide-menubar --role="terminal-3" &
