#!/bin/sh

thunar ~/Downloads &

xfce4-terminal --default-working-directory=/home/seiji/ --hide-menubar &
xfce4-terminal --default-working-directory=/home/seiji/Documents --hide-menubar &
xfce4-terminal --default-working-directory=/ --hide-menubar &

# trackma-gtk &

deluge &

sleep 6 && devilspie &
