#!/bin/sh

deluge &
thunar ~/Downloads &

xfce4-terminal --default-working-directory=/home/seiji/ --hide-menubar &
xfce4-terminal --default-working-directory=/home/seiji/Documents --hide-menubar &
xfce4-terminal --default-working-directory=/ --hide-menubar &

sleep 7 && devilspie &
