#!/bin/sh

thunar &

xfce4-terminal --default-working-directory=/home/seiji/ --hide-menubar &
xfce4-terminal --default-working-directory=/home/seiji/Documents --hide-menubar &
xfce4-terminal --default-working-directory=/ --hide-menubar &

sleep 3 && devilspie &
