#!/bin/bash

res=$(echo "   Logout;    Restart;    Shutdown;Cancel" | rofi -sep ";" -dmenu -p "Power:" -hide-scrollbar -theme sysmenu)

if [[ $res = *"Logout"* ]]; then
    i3-msg exit
fi
if [[ $res = *"Restart"* ]]; then
    systemctl reboot
fi
if [[ $res = *"Shutdown"* ]]; then
    systemctl poweroff
fi
exit 0
