#!/usr/bin/env bash

dir=$(dirname $0)
source $dir/util.sh

short=""
status=0

URL='http://www.accuweather.com/en/us/cincinnati-oh/45212/weather-forecast/350126'
SITE="$(curl -s "$URL")"

temp="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $10 }'| head -1)"

echo "$temp°"
exit $status
